- name: bootstrap
  shell: python {{deploy_root}}/manage.py bootstrap --app
- name: ensure private config
  shell: python {{deploy_root}}/manage.py ensure-secret {{deploy_root}}/conf.d/000-private.yml
- name: migrate db
  shell: cd {{deploy_root}} && python manage.py db upgrade
- name: fix permissions
  shell: chown -R {{user_name}}:{{group_name}} {{deploy_root}}
- name: ensure nginx configuration
  shell: python {{deploy_root}}/manage.py generate_nginx_config /etc/nginx/sites-enabled/{{app_name}}.conf
  notify: reload nginx config
- name: reload supervisor
  shell: supervisorctl reload
  when: in_docker is not defined
- name: ensure supervisor service
  action: service name=supervisor state=started
  when: in_docker is not defined
- name: try to get local page
  shell: curl http://localhost/
