---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install required Packages for RedHat
  yum: name={{ item }} state=installed
  with_items: openldap_server_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install required Packages for Ubuntu
  apt: name={{ item }} state=installed update_cache=yes
  with_items: openldap_server_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: Delete the openldap configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  register: root_password

- name: Copy the slapd.conf configuration file for Redhat
  template: src=slapd.conf.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf_ubuntu.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify: 
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf

- name: Copy DHCP ldap schema for Ubuntu
  copy: src=dhcp.schema dest={{ openldap_server_app_path }}/schema/dhcp.schema
  when: ansible_os_family == "Debian"
  notify:
  - restart slapd

- name: Configure DHCP with Ldap Backend for Ubuntu
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0644
  when: ansible_os_family == "Debian"

- debug: var=dhcp_interfaces

- name: Update DHCP Daemon startup configuration for Ubuntu
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server owner=root group=root mode=0644
  when: ansible_os_family == "Debian"

- name: Create DHCPd log file directory
  file: path=/var/log/dhcpd state=directory owner=root group=root mode=755

- name: Remove AppArmor
  apt: name={{ item }} state=absent
  with_items:
    - apparmor
    - apparmor-utils
  when: ansible_os_family == "Debian"
