"""empty message

Revision ID: 16e8a2e037bf
Revises: 8899e65208c
Create Date: 2015-04-15 15:13:26.208945

"""

# revision identifiers, used by Alembic.
revision = '16e8a2e037bf'
down_revision = '8899e65208c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
