"""empty message

Revision ID: 1b680fa316d
Revises: None
Create Date: 2015-02-26 17:54:04.197581

"""

# revision identifiers, used by Alembic.
revision = '1b680fa316d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('netmask', sa.String(length=255), nullable=True),
    sa.Column('broadcast_address', sa.String(length=255), nullable=True),
    sa.Column('routers', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mac', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host')
    op.drop_table('IP')
    op.drop_table('group')
    op.drop_table('subnet')
    ### end Alembic commands ###
