"""empty message

Revision ID: 2c998c3f8312
Revises: 16e8a2e037bf
Create Date: 2015-04-15 21:25:21.741628

"""

# revision identifiers, used by Alembic.
revision = '2c998c3f8312'
down_revision = '16e8a2e037bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
