"""empty message

Revision ID: 389b352e8756
Revises: 5a0ff78f1597
Create Date: 2015-05-10 17:18:13.441640

"""

# revision identifiers, used by Alembic.
revision = '389b352e8756'
down_revision = '5a0ff78f1597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IP', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('host', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('pool', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('range', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('subnet', sa.Column('deployed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subnet', 'deployed')
    op.drop_column('range', 'deployed')
    op.drop_column('pool', 'deployed')
    op.drop_column('host', 'deployed')
    op.drop_column('group', 'deployed')
    op.drop_column('IP', 'deployed')
    ### end Alembic commands ###
