"""empty message

Revision ID: 8899e65208c
Revises: 1b680fa316d
Create Date: 2015-04-13 13:24:17.754286

"""

# revision identifiers, used by Alembic.
revision = '8899e65208c'
down_revision = '1b680fa316d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
